version: '3.7'
services:
  rabbitmq:
    build:
      context: rabbitmq/
    container_name: canren-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - java—tools
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

networks:
  java—tools:
    driver: bridge
  