version: '3.7'
services:
  rabbitmq:
    build:
      context: rabbitmq/
      args:
        RABBITMQ_VERSION: $RABBITMQ_VERSION
    container_name: tools-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - java—tools
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    restart: always

  mysql:
    build:
      context: mysql/
      args:
        MYSQL_VERSION: $MYSQL_VERSION
    container_name: tools-mysql
    ports:
      - 3306:3306
    networks:
      - java—tools
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:cached
      - ../data/mysql:/var/lib/mysql
      - ../logs/mysql:/var/lib/mysql-logs
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    restart: always
    command: "--character-set-server=utf8"

  redis:
    build:
      context: redis/
      args:
        REDIS_VERSION: $REDIS_VERSION
    container_name: tools-redis
    ports:
      - 6379:6379
    networks:
      - java—tools
    volumes:
      - ./redis/redis.conf:/etc/redis.conf:cached
      - ../data/redis:/data
    command: "/etc/redis.conf --requirepass 123456"
    restart: always

  nacos: # 访问地址 http://localhost:端口号/nacos 帐号密码均为nacos
    build:
      context: nacos/
      args:
        NACOS_VERSION: $NACOS_VERSION
    container_name: tools-nacos
    ports:
      - 8848:8848
    networks:
      - java—tools
    environment:
      MODE: standalone
    restart: always

networks:
  java—tools:
    driver: bridge